version: '3'

services:
  video-streaming:
    image: node-video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
      target: dev
    container_name: node-video-streaming
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - "NODE_ENV=development"
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - "./video-streaming/src:/usr/src/app/src:z"
    restart: 'no'

  video-storage:
    image: node-video-storage
    build:
      context: ./video-storage-azure
      dockerfile: Dockerfile
      target: dev
    container_name: node-video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - "NODE_ENV=development"
    volumes:
      - /tmp/video-storage-azure/npm-cache:/root/.npm:z
      - "./video-storage-azure/src:/usr/src/app/src:z"
    restart: 'no'

  db:
    image: mongo:4.2
    container_name: node-db
    ports:
      - "4002:27017"
    restart: always

  history:
    image: node-history
    build:
      context: ./history
      dockerfile: Dockerfile
      target: dev
    container_name: node-history
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - "NODE_ENV=development"
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - "./history/src:/usr/src/app/src:z"
    restart: 'no'
    